application: ffclean
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:

  - url: /
    static_files: index.html
    upload: index.html

  - url: /css
    static_dir: css

  - url: /fonts
    static_dir: fonts

  # Serve images as static resources.
  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: .+\.(gif|png|jpg)$
    application_readable: true

  - url: /(.+\.(htm|html|css|js))$
    static_files: \1
    upload: (.+\.(htm|html|css|js))$
    application_readable: true

  - url: /(.+\.php)$
    script: \1
    login: admin

  - url: /admin/.*
    script: admin.app
    login: admin

  - url: /.*
    script: not_found.app
